# GitHub action to run Clarinet tests against the contracts
# and fail if code is invalid or a test fails.

name: Test Contracts

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop
  # allow running manually
  workflow_dispatch:

env:
  CLARINET_DISABLE_HINTS: 1

jobs:
  test-contracts:
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout code"
        uses: actions/checkout@v4
      - name: "Check contract syntax"
        uses: docker://hirosystems/clarinet:2.6.0
        with:
          args: check
